name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller imagehash numpy Pillow

      - name: Build the EXE file with PyInstaller
        run: |
          pyinstaller --clean --onefile --noconsole --name="Image Duplication Detector" --hidden-import=imagehash -p ./src src/gui.py

      - name: Upload EXE as a release asset
        uses: actions/upload-artifact@v4
        with:
          name: Image-Duplication-Detector-Windows
          path: dist/"Image Duplication Detector".exe
