name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller imagehash numpy Pillow

      - name: Build the EXE file with PyInstaller
        run: |
          pyinstaller --clean --onefile --noconsole --name="Image Duplication Detector" --hidden-import=imagehash -p ./src src/gui.py
      
      # Step for Release builds (runs on tag pushes)
      - name: Create and Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="${{ github.ref }}"
          RELEASE_URL=$(gh release create "${RELEASE_TAG}" --generate-notes --title "Release ${RELEASE_TAG}" --draft=false --prerelease=false --repo "${{ github.repository }}" | tail -1)
          gh release upload "${RELEASE_TAG}" "dist/Image Duplication Detector.exe" --repo "${{ github.repository }}" --clobber

      # Step for Artifact builds (runs on manual triggers)
      - name: Upload Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: Image-Duplication-Detector-Windows
          path: dist/Image Duplication Detector.exe