name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller imagehash numpy Pillow

      - name: Build the EXE file with PyInstaller
        run: |
          pyinstaller --clean --onefile --noconsole --name="Image Duplication Detector" --hidden-import=imagehash -p ./src src/gui.py

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Image Duplication Detector.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
              ### Release Notes 📝
              - Added two buttons: "Dry Run" and "Show Full Logs"
              - Both buttons are checked → Shows full logs WITHOUT actually deleting
              - Only "Dry Run" is checked → Shows short logs WITHOUT actually deleting
              - Both are NOT checked → Normal operating mode. Deletes duplicate images
